### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by ainesh01** [shravanhariharan2/auction-system#1]
sus

**Comment by ainesh01** [comment]
![image](https://user-images.githubusercontent.com/20953846/151636449-abf279f7-1cd2-4978-b2e5-bc1c0b401eec.png)

**Comment by ainesh01** [comment]
@shravanhariharan2

**Comment by shravanhariharan2** [comment]
not sus enough for implementation.

**Comment by ainesh01** [comment]
![image](https://user-images.githubusercontent.com/20953846/152945419-9583a36a-a05c-487f-881c-3dd40f173495.png)
